### ISSUE TITLE
chroma_format_idc defaults to 1 if not specified

### ISSUE THREAD

**Issue by koush** [gliese1337/HLS.js#25]
https://github.com/gliese1337/HLS.js/blob/cf92dd2764a121af611b048374896a815110564b/spsparser/src/index.ts#L79

**Comment by koush** [comment]
This is causing my resolution calculation to fail, as it is always reporting the format as monochrome.

**Comment by gliese1337** [comment]
Just pushed an update and republished the SPS parser package with minor version 0.2.1. Thanks for the very specific diagnosis!
