### ISSUE TITLE
PMT decode fails to recognise AAC audio

### ISSUE THREAD

**Issue by nielslaukens** [gliese1337/HLS.js#31]
Hi,

I needed to parse MPEG-TS in the browser, and came across this project which looks absolutely great. Thanks for your work!

I have however run into a problem: I can't seem to get audio packets demuxed. I've debugged the code, and I believe I have found a bug in the PMT parsing logic:

Assume a PMT with an entry for audio PID 0x22 encoded with AAC (stream_type 0x0f). The PMT will contain (hex): `0f e0 22`. During parsing, https://github.com/gliese1337/HLS.js/blob/master/demuxer/src/pmt.ts#L125 will map the `0x0f` into `stream_type.aac_audio`, which [equals 7](https://github.com/gliese1337/HLS.js/blob/master/demuxer/src/stream.ts#L14).
[Later in the same function](https://github.com/gliese1337/HLS.js/blob/master/demuxer/src/pmt.ts#L135), this type is mapped *again* by a call to `get_media_type()`, but that function doesn't recognise the value `7`/`stream_type.aac_audio`. This results in `stream_type.unknown`, which is ignored for further decoding.

I tried to understand why the mapping is done in two phases, so I could create a Pull Request with a patch. But I don't understand the logic behind the code (yet). Also, AAC seems to be a very popular codec nowadays, so I'm a bit surprised this doesn't "just work" and I suspect I may be missing things...

Thank you in advance for looking into this

**Comment by gliese1337** [comment]
Thanks for the detailed report, I'll take a look at it! It would be helpful if you could provide a sample file that triggers the problem.

**Comment by gliese1337** [comment]
Just opened a PR that should fix this; the key changes are https://github.com/gliese1337/HLS.js/pull/32/files#diff-f5194a1d1f4debda3eff1a8eae179c4383f83552b9c7d81c5814678db0412c74R125 and https://github.com/gliese1337/HLS.js/pull/32/files#diff-f5194a1d1f4debda3eff1a8eae179c4383f83552b9c7d81c5814678db0412c74R136

There are some additional housekeeping changes that should make similar errors more difficult to reintroduce in the future.
If you can pull that branch and verify the fix on your data, I'll merge it and publish a new package version.

**Comment by nielslaukens** [comment]
Wow, that was fast!

That PR indeed fixes the issue. Thank you!

One more detail: I'm pulling this in via `npm install ts-demuxer`, will that also be updated when you merge this? What version-requirements should I pin to ensure I have this patch?

**Comment by gliese1337** [comment]
Yes, it will. I just did the merge and re-published to NPM. The new version is ts-demuxer@1.1.1
